on: [push]

jobs:
  run-archi-cli:
    runs-on: ubuntu-latest
    name: Run Archi CLI
    steps:
      - uses: actions/checkout@v3
      - name: Archi CLI Report
        id: archi-cli
        uses: mgudmund/archi-action@v1.9
        with:
          options: '--html.createReport docs'
      - name: ls
        run: ls -la
      - name: pwd
        run: pwd
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
